In [1]:
print("Okay")

Okay

In [2]:
import pandas as pd

df = pd.read_csv("covid_toy_practice.csv")
df

    gender  fever   cough        city   age has_covid
0     Male    103    Mild       Dhaka  35.0       Yes
1   Female    101  Strong  Chittagong  42.0       Yes
2   Female     98    Mild       Dhaka  23.0        No
3     Male    100  Strong      Khulna  51.0       Yes
4   Female     99    Mild    Rajshahi   NaN        No
5     Male    104  Strong       Dhaka  60.0       Yes
6   Female     97    Mild      Sylhet  29.0        No
7     Male    102  Strong      Khulna   NaN       Yes
8   Female     99    Mild       Dhaka  31.0        No
9     Male    100  Strong    Rajshahi  47.0       Yes
10  Female     98    Mild  Chittagong  26.0        No
11    Male    101  Strong      Sylhet  55.0       Yes

In [3]:
df.head()

   gender  fever   cough        city   age has_covid
0    Male    103    Mild       Dhaka  35.0       Yes
1  Female    101  Strong  Chittagong  42.0       Yes
2  Female     98    Mild       Dhaka  23.0        No
3    Male    100  Strong      Khulna  51.0       Yes
4  Female     99    Mild    Rajshahi   NaN        No

In [4]:
df.shape

(12, 6)

In [5]:
df.isnull().sum()

gender       0
fever        0
cough        0
city         0
age          2
has_covid    0
dtype: int64

# Feature and Target split

In [6]:
df.head(2)

   gender  fever   cough        city   age has_covid
0    Male    103    Mild       Dhaka  35.0       Yes
1  Female    101  Strong  Chittagong  42.0       Yes

In [7]:
X = df.drop(columns=["has_covid"])
y = df["has_covid"]

X

    gender  fever   cough        city   age
0     Male    103    Mild       Dhaka  35.0
1   Female    101  Strong  Chittagong  42.0
2   Female     98    Mild       Dhaka  23.0
3     Male    100  Strong      Khulna  51.0
4   Female     99    Mild    Rajshahi   NaN
5     Male    104  Strong       Dhaka  60.0
6   Female     97    Mild      Sylhet  29.0
7     Male    102  Strong      Khulna   NaN
8   Female     99    Mild       Dhaka  31.0
9     Male    100  Strong    Rajshahi  47.0
10  Female     98    Mild  Chittagong  26.0
11    Male    101  Strong      Sylhet  55.0

In [8]:
y

0     Yes
1     Yes
2      No
3     Yes
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10     No
11    Yes
Name: has_covid, dtype: object

# Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
X_train.shape

(9, 5)

In [13]:
X_test.shape

(3, 5)

# SimpleImputer example

In [14]:
from sklearn.impute import SimpleImputer

si = SimpleImputer()

X_train_age = si.fit_transform(X_train[["age"]])
X_test_age = si.transform(X_test[["age"]])

# OneHotEncoder example

In [15]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

X_train_city = ohe.fit_transform(X_train[["city"]])
X_test_city = ohe.transform(X_test[["city"]])

# OrdinalEncoder example

In [16]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[["Mild", "Strong"]])

X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.transform(X_test[["cough"]])

# ColumnTransformer example

In [17]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(
    transformers=[
        ("age_imputer", SimpleImputer(), ["age"]),
        ("city_ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False), ["city"]),
        ("cough_oe", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"])
    ],
    remainder="passthrough"
)

In [18]:
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [19]:
X_train_transformed

array([[31.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 'Female', 99],
       [60.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 'Male', 104],
       [23.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 'Female', 98],
       [42.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 'Female', 101],
       [55.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 'Male', 101],
       [41.57142857142857, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 'Female', 99],
       [41.57142857142857, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 'Male', 102],
       [51.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 'Male', 100],
       [29.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 'Female', 97]], dtype=object)

In [20]:
X_test_transformed

array([[26.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Female', 98],
       [47.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 'Male', 100],
       [35.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 'Male', 103]], dtype=object)